
	class Project_Primaris_Dos
	{
		author="me";
		name="Project Primaris";
		requiredAddons[]=
		{
			"TIOWSpaceMarines",
			"A3_Data_F",
			"A3_Characters_F",
			"A3_Anims_F"
		};
		requiredVersion=0.1;
		units[]=
		{
			"Primaris_Dos_PP_BS_1",
			"Primaris_Dos_PP_BS_2",
			"Primaris_Dos_PP_BS_3",
			"Primaris_Dos_PP_BS_4",
			"Primaris_Dos_PP_BS_5",
			"Primaris_Dos_PP_BS_6",
			"Primaris_Dos_PP_BS_7",
			"Primaris_Dos_PP_UM_1",
			"Primaris_Dos_PP_UM_2",
			"Primaris_Dos_PP_UM_3",
			"Primaris_Dos_PP_UM_4",
			"Primaris_Dos_PP_UM_5",
			"Primaris_Dos_PP_UM_6",
			"Primaris_Dos_PP_UM_7",
			"Primaris_Dos_PP_BT_1",
			"Primaris_Dos_PP_BT_2",
			"Primaris_Dos_PP_BT_3",
			"Primaris_Dos_PP_BT_4",
			"Primaris_Dos_PP_BT_5",
			"Primaris_Dos_PP_BT_6",
			"Primaris_Dos_PP_BT_7",
			"Primaris_Dos_PP_DA_1",
			"Primaris_Dos_PP_DA_2",
			"Primaris_Dos_PP_DA_3",
			"Primaris_Dos_PP_DA_4",
			"Primaris_Dos_PP_DA_5",
			"Primaris_Dos_PP_DA_6",
			"Primaris_Dos_PP_DA_7",
			"Primaris_Dos_PP_IF_1",
			"Primaris_Dos_PP_IF_2",
			"Primaris_Dos_PP_IF_3",
			"Primaris_Dos_PP_IF_4",
			"Primaris_Dos_PP_IF_5",
			"Primaris_Dos_PP_IF_6",
			"Primaris_Dos_PP_IF_7",
			"Primaris_Dos_PP_SAL_1",
			"Primaris_Dos_PP_SAL_2",
			"Primaris_Dos_PP_SAL_3",
			"Primaris_Dos_PP_SAL_4",
			"Primaris_Dos_PP_SAL_5",
			"Primaris_Dos_PP_SAL_6",
			"Primaris_Dos_PP_SAL_7",
			"Primaris_Dos_PP_WS_1",
			"Primaris_Dos_PP_WS_2",
			"Primaris_Dos_PP_WS_3",
			"Primaris_Dos_PP_WS_4",
			"Primaris_Dos_PP_WS_5",
			"Primaris_Dos_PP_WS_6",
			"Primaris_Dos_PP_WS_7",
			"Primaris_Dos_PP_SW_1",
			"Primaris_Dos_PP_SW_2",
			"Primaris_Dos_PP_SW_3",
			"Primaris_Dos_PP_SW_4",
			"Primaris_Dos_PP_SW_5",
			"Primaris_Dos_PP_SW_6",
			"Primaris_Dos_PP_SW_7",
			"Primaris_SM_BS_1",
			"Primaris_SM_BS_2",
			"Primaris_SM_BS_3",
			"Primaris_SM_BS_4",
			"Primaris_SM_BS_5",
			"Primaris_SM_BS_6",
			"Primaris_SM_BS_7",
			"Primaris_SM_BS_8",
			"Primaris_SM_UM_1",
			"Primaris_SM_UM_2",
			"Primaris_SM_UM_3",
			"Primaris_SM_UM_4",
			"Primaris_SM_UM_5",
			"Primaris_SM_UM_6",
			"Primaris_SM_UM_7",
			"Primaris_SM_UM_8",
			"Primaris_SM_BT_1",
			"Primaris_SM_BT_2",
			"Primaris_SM_BT_3",
			"Primaris_SM_BT_4",
			"Primaris_SM_BT_5",
			"Primaris_SM_BT_6",
			"Primaris_SM_BT_7",
			"Primaris_SM_BT_8",
			"Primaris_SM_DA_1",
			"Primaris_SM_DA_2",
			"Primaris_SM_DA_3",
			"Primaris_SM_DA_4",
			"Primaris_SM_DA_5",
			"Primaris_SM_DA_6",
			"Primaris_SM_DA_7",
			"Primaris_SM_DA_8",
			"Primaris_SM_IF_1",
			"Primaris_SM_IF_2",
			"Primaris_SM_IF_3",
			"Primaris_SM_IF_4",
			"Primaris_SM_IF_5",
			"Primaris_SM_IF_6",
			"Primaris_SM_IF_7",
			"Primaris_SM_IF_8",
			"Primaris_SM_SAL_1",
			"Primaris_SM_SAL_2",
			"Primaris_SM_SAL_3",
			"Primaris_SM_SAL_4",
			"Primaris_SM_SAL_5",
			"Primaris_SM_SAL_6",
			"Primaris_SM_SAL_7",
			"Primaris_SM_SAL_8",
			"Primaris_SM_WS_1",
			"Primaris_SM_WS_2",
			"Primaris_SM_WS_3",
			"Primaris_SM_WS_4",
			"Primaris_SM_WS_5",
			"Primaris_SM_WS_6",
			"Primaris_SM_WS_7",
			"Primaris_SM_WS_8",
			"Primaris_SM_SW_1",
			"Primaris_SM_SW_2",
			"Primaris_SM_SW_3",
			"Primaris_SM_SW_4",
			"Primaris_SM_SW_5",
			"Primaris_SM_SW_6",
			"Primaris_SM_SW_7",
			"Primaris_SM_SW_8"
		};
		weapons[]=
		{
			"Primaris_SM_BS_1_W",
			"Primaris_SM_BS_2_W",
			"Primaris_SM_BS_3_W",
			"Primaris_SM_BS_4_W",
			"Primaris_SM_BS_5_W",
			"Primaris_SM_BS_6_W",
			"Primaris_SM_BS_7_W",
			"Primaris_SM_BS_8_W",
			"Primaris_SM_UM_1_W",
			"Primaris_SM_UM_2_W",
			"Primaris_SM_UM_3_W",
			"Primaris_SM_UM_4_W",
			"Primaris_SM_UM_5_W",
			"Primaris_SM_UM_6_W",
			"Primaris_SM_UM_7_W",
			"Primaris_SM_UM_8_W",
			"Primaris_SM_BT_1_W",
			"Primaris_SM_BT_2_W",
			"Primaris_SM_BT_3_W",
			"Primaris_SM_BT_4_W",
			"Primaris_SM_BT_5_W",
			"Primaris_SM_BT_6_W",
			"Primaris_SM_BT_7_W",
			"Primaris_SM_BT_8_W",
			"Primaris_SM_DA_1_W",
			"Primaris_SM_DA_2_W",
			"Primaris_SM_DA_3_W",
			"Primaris_SM_DA_4_W",
			"Primaris_SM_DA_5_W",
			"Primaris_SM_DA_6_W",
			"Primaris_SM_DA_7_W",
			"Primaris_SM_DA_8_W",
			"Primaris_SM_IF_1_W",
			"Primaris_SM_IF_2_W",
			"Primaris_SM_IF_3_W",
			"Primaris_SM_IF_4_W",
			"Primaris_SM_IF_5_W",
			"Primaris_SM_IF_6_W",
			"Primaris_SM_IF_7_W",
			"Primaris_SM_IF_8_W",
			"Primaris_SM_SAL_1_W",
			"Primaris_SM_SAL_2_W",
			"Primaris_SM_SAL_3_W",
			"Primaris_SM_SAL_4_W",
			"Primaris_SM_SAL_5_W",
			"Primaris_SM_SAL_6_W",
			"Primaris_SM_SAL_7_W",
			"Primaris_SM_SAL_8_W",
			"Primaris_SM_WS_1_W",
			"Primaris_SM_WS_2_W",
			"Primaris_SM_WS_3_W",
			"Primaris_SM_WS_4_W",
			"Primaris_SM_WS_5_W",
			"Primaris_SM_WS_6_W",
			"Primaris_SM_WS_7_W",
			"Primaris_SM_WS_8_W",
			"Primaris_SM_SW_1_W",
			"Primaris_SM_SW_2_W",
			"Primaris_SM_SW_3_W",
			"Primaris_SM_SW_4_W",
			"Primaris_SM_SW_5_W",
			"Primaris_SM_SW_6_W",
			"Primaris_SM_SW_7_W",
			"Primaris_SM_SW_8_W",
			"Primaris_Helm_Main_BS_1",
			"Primaris_Helm_Main_BS_2",
			"Primaris_Helm_Main_BS_3",
			"Primaris_Helm_Main_BS_4",
			"Primaris_Helm_Main_BS_5",
			"Primaris_Helm_Main_BS_6",
			"Primaris_Helm_Main_BS_7",
			"Primaris_Helm_Main_UM_1",
			"Primaris_Helm_Main_UM_2",
			"Primaris_Helm_Main_UM_3",
			"Primaris_Helm_Main_UM_4",
			"Primaris_Helm_Main_UM_5",
			"Primaris_Helm_Main_UM_6",
			"Primaris_Helm_Main_UM_7",
			"Primaris_Helm_Main_BT_1",
			"Primaris_Helm_Main_BT_2",
			"Primaris_Helm_Main_BT_3",
			"Primaris_Helm_Main_BT_4",
			"Primaris_Helm_Main_BT_5",
			"Primaris_Helm_Main_BT_6",
			"Primaris_Helm_Main_BT_7",
			"Primaris_Helm_Main_DA_1",
			"Primaris_Helm_Main_DA_2",
			"Primaris_Helm_Main_DA_3",
			"Primaris_Helm_Main_DA_4",
			"Primaris_Helm_Main_DA_5",
			"Primaris_Helm_Main_DA_6",
			"Primaris_Helm_Main_DA_7",
			"Primaris_Helm_Main_IF_1",
			"Primaris_Helm_Main_IF_2",
			"Primaris_Helm_Main_IF_3",
			"Primaris_Helm_Main_IF_4",
			"Primaris_Helm_Main_IF_5",
			"Primaris_Helm_Main_IF_6",
			"Primaris_Helm_Main_IF_7",
			"Primaris_Helm_Main_SAL_1",
			"Primaris_Helm_Main_SAL_2",
			"Primaris_Helm_Main_SAL_3",
			"Primaris_Helm_Main_SAL_4",
			"Primaris_Helm_Main_SAL_5",
			"Primaris_Helm_Main_SAL_6",
			"Primaris_Helm_Main_SAL_7",
			"Primaris_Helm_Main_WS_1",
			"Primaris_Helm_Main_WS_2",
			"Primaris_Helm_Main_WS_3",
			"Primaris_Helm_Main_WS_4",
			"Primaris_Helm_Main_WS_5",
			"Primaris_Helm_Main_WS_6",
			"Primaris_Helm_Main_WS_7",
			"Primaris_Helm_Main_SW_1",
			"Primaris_Helm_Main_SW_2",
			"Primaris_Helm_Main_SW_3",
			"Primaris_Helm_Main_SW_4",
			"Primaris_Helm_Main_SW_5",
			"Primaris_Helm_Main_SW_6",
			"Primaris_Helm_Main_SW_7",
			"Primaris_Vest_40K_BS_1",
			"Primaris_Vest_40K_BS_2",
			"Primaris_Vest_40K_BS_3",
			"Primaris_Vest_40K_BS_4",
			"Primaris_Vest_40K_BS_5",
			"Primaris_Vest_40K_BS_6",
			"Primaris_Vest_40K_BS_7",
			"Primaris_Vest_40K_BS_8",
			"Primaris_Vest_40k_UM_1",
			"Primaris_Vest_40k_UM_2",
			"Primaris_Vest_40k_UM_3",
			"Primaris_Vest_40k_UM_4",
			"Primaris_Vest_40k_UM_5",
			"Primaris_Vest_40k_UM_6",
			"Primaris_Vest_40k_UM_7",
			"Primaris_Vest_40k_UM_8",
			"Primaris_Vest_40k_BT_1",
			"Primaris_Vest_40k_BT_2",
			"Primaris_Vest_40k_BT_3",
			"Primaris_Vest_40k_BT_4",
			"Primaris_Vest_40k_BT_5",
			"Primaris_Vest_40k_BT_6",
			"Primaris_Vest_40k_BT_7",
			"Primaris_Vest_40k_BT_8",
			"Primaris_Vest_40k_DA_1",
			"Primaris_Vest_40k_DA_2",
			"Primaris_Vest_40k_DA_3",
			"Primaris_Vest_40k_DA_4",
			"Primaris_Vest_40k_DA_5",
			"Primaris_Vest_40k_DA_6",
			"Primaris_Vest_40k_DA_7",
			"Primaris_Vest_40k_DA_8",
			"Primaris_Vest_40k_IF_1",
			"Primaris_Vest_40k_IF_2",
			"Primaris_Vest_40k_IF_3",
			"Primaris_Vest_40k_IF_4",
			"Primaris_Vest_40k_IF_5",
			"Primaris_Vest_40k_IF_6",
			"Primaris_Vest_40k_IF_7",
			"Primaris_Vest_40k_IF_8",
			"Primaris_Vest_40k_SAL_1",
			"Primaris_Vest_40k_SAL_2",
			"Primaris_Vest_40k_SAL_3",
			"Primaris_Vest_40k_SAL_4",
			"Primaris_Vest_40k_SAL_5",
			"Primaris_Vest_40k_SAL_6",
			"Primaris_Vest_40k_SAL_7",
			"Primaris_Vest_40k_SAL_8",
			"Primaris_Vest_40k_WS_1",
			"Primaris_Vest_40k_WS_2",
			"Primaris_Vest_40k_WS_3",
			"Primaris_Vest_40k_WS_4",
			"Primaris_Vest_40k_WS_5",
			"Primaris_Vest_40k_WS_6",
			"Primaris_Vest_40k_WS_7",
			"Primaris_Vest_40k_WS_8",
			"Primaris_Vest_40k_SW_1",
			"Primaris_Vest_40k_SW_2",
			"Primaris_Vest_40k_SW_3",
			"Primaris_Vest_40k_SW_4",
			"Primaris_Vest_40k_SW_5",
			"Primaris_Vest_40k_SW_6",
			"Primaris_Vest_40k_SW_7",
			"Primaris_Vest_40k_SW_8",
			"Primaris_Elim_Hood_Up",
			"Primaris_Elim_Hood_Down"
		};
		worlds[]={};
	};
class CfgVehicles
{

// Power Packs

  class TIOW_Mk4Powerpack_Ultra;
	class Primaris_Dos_PP_SR_1: TIOW_Mk4Powerpack_Ultra
	{
		scope=2;
		displayName="Mk.10 Powerpack (TSR Blackshield)";
		model="Project_Primaris_D_Main\Models\Power_Pack_Main.p3d";
		hiddenSelections[]=
		{
			"Camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"SR_Primaris\Textures\SR_PrimArmour.paa"
		};
		maximumLoad=500;
		class TransportMagazines
		{
		};
		class TransportItems
		{
		};
		tf_hasLRradio=1;
		tf_range=50000;
		tf_encryptionCode="tf_west_radio_code";
		tf_dialog="rt1523g_radio_dialog";
		tf_subtype="digital_lr";
		tf_dialogUpdate="call TFAR_fnc_updateLRDialogToChannel;";
	};

	// Power Armors

		class TIOWSpaceMarine1;
	class TIOW_Tactical_BT_3;
	class Primaris_SM_SR_1: TIOW_Tactical_BT_3
	{
		scope=2;
		scopeArsenal=2;
		scopeCurator=2;
		model="Project_Primaris_D_Main\Models\Base_Brother.p3d";
		displayName="Primaris Brother (Mk.10)";
		uniformClass="Primaris_SM_BS_1_W";
		faction="Dos_Primaris_SpaceMarines";
		editorSubcategory="EdSubcat_BloodAngels";
		backpack="Primaris_Dos_PP_BS_1";
		linkedItems[]=
		{
			"Primaris_Vest_40K_BS_1",
			"Primaris_Helm_Main_BS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		RespawnLinkedItems[]=
		{
			"Primaris_Vest_40K_BS_1",
			"Primaris_Helm_Main_BS_1",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		hiddenSelections[]=
		{
			"Camo2",
			"Camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"SR_Primaris\Textures\SR_PrimArmour.paa",
			"SR_Uniforms\Textures\SR_Armour1.paa"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"Primaris_Dos_Bolt_Rifle"
		};
		magazines[]=
		{
			"Primaris_Dos_Bolt_RifleMag",
			"Primaris_Dos_Bolt_RifleMag",
			"Primaris_Dos_Bolt_RifleMag",
			"Primaris_Dos_Bolt_RifleMag",
			"TIOW_sm_frag_grenade_mag",
			"TIOW_sm_frag_grenade_mag",
			"TIOW_sm_krak_grenade_mag",
			"TIOW_sm_smoke_grenade_mag"
		};
		respawnweapons[]=
		{
			"Throw",
			"Put",
			"Primaris_Dos_Bolt_Rifle"
		};
		respawnMagazines[]=
		{
			"Primaris_Dos_Bolt_RifleMag",
			"Primaris_Dos_Bolt_RifleMag",
			"Primaris_Dos_Bolt_RifleMag",
			"Primaris_Dos_Bolt_RifleMag",
			"TIOW_sm_frag_grenade_mag",
			"TIOW_sm_frag_grenade_mag",
			"TIOW_sm_krak_grenade_mag",
			"TIOW_sm_smoke_grenade_mag"
		};
	};
	class Primaris_SM_Lysander: Primaris_SM_SR_1
	{
		displayName="Primaris Lysander (Mk.10)";
		hiddenSelectionsTextures[]=
		{
			"SR_Primaris\Textures\Lysander_PrimArmour.paa",
			"SR_Uniforms\Textures\SR_Armour1.paa"
		};
	}
		class Primaris_SR_BloodAngels: Primaris_SM_SR_1
	{
		author="Hummus, Barbon";
		displayName="Primaris BA (Mk.10)";
		hiddenSelectionsTextures[]=
		{
			"SR_Primaris\Textures\BA_PrimArmour.paa",
			"SR_Uniforms\Textures\SR_Armour1.paa"
		};
	}
	class Primaris_SR_DarkAngels: Primaris_SM_SR_1
	{
		author="Hummus, Barbon";
		displayName="Primaris DA (Mk.10)";
		hiddenSelectionsTextures[]=
		{
			"SR_Primaris\Textures\DA_PrimArmour.paa",
			"SR_Uniforms\Textures\SR_Armour1.paa"
		};
	}
	class Primaris_SR_FleshTearers: Primaris_SM_SR_1
	{
		author="Hummus, Barbon";
		displayName="Primaris FT (Mk.10)";
		hiddenSelectionsTextures[]=
		{
			"SR_Primaris\Textures\FT_PrimArmour.paa",
			"SR_Uniforms\Textures\SR_Armour1.paa"
		};
	}
	class Primaris_SR_ImperialFists: Primaris_SM_SR_1
	{
		author="Hummus, Barbon";
		displayName="Primaris IF (Mk.10)";
		hiddenSelectionsTextures[]=
		{
			"SR_Primaris\Textures\IF_PrimArmour.paa",
			"SR_Uniforms\Textures\SR_Armour1.paa"
		};
	}
	class Primaris_SR_IronHands: Primaris_SM_SR_1
	{
		author="Hummus, Barbon";
		displayName="Primaris IH (Mk.10)";
		hiddenSelectionsTextures[]=
		{
			"SR_Primaris\Textures\IH_PrimArmour.paa",
			"SR_Uniforms\Textures\SR_Armour1.paa"
		};
	}
	class Primaris_SR_RavenGuard: Primaris_SM_SR_1
	{
		author="Hummus, Barbon";
		displayName="Primaris RG (Mk.10)";
		hiddenSelectionsTextures[]=
		{
			"SR_Primaris\Textures\RG_PrimArmour.paa",
			"SR_Uniforms\Textures\SR_Armour1.paa"
		};
	}
	class Primaris_SR_Salamanders: Primaris_SM_SR_1
	{
		author="Hummus, Barbon";
		displayName="Primaris SAL (Mk.10)";
		hiddenSelectionsTextures[]=
		{
			"SR_Primaris\Textures\SAL_PrimArmour.paa",
			"SR_Uniforms\Textures\SR_Armour1.paa"
		};
	}
	class Primaris_SR_SpaceWolves: Primaris_SM_SR_1
	{
		author="Hummus, Barbon";
		displayName="Primaris SW (Mk.10)";
		hiddenSelectionsTextures[]=
		{
			"SR_Primaris\Textures\SW_PrimArmour.paa",
			"SR_Uniforms\Textures\SR_Armour1.paa"
		};
	}
	class Primaris_SR_Ultramarines: Primaris_SM_SR_1
	{
		author="Hummus, Barbon";
		displayName="Primaris UM (Mk.10)";
		hiddenSelectionsTextures[]=
		{
			"SR_Primaris\Textures\UM_PrimArmour.paa",
			"SR_Uniforms\Textures\SR_Armour1.paa"
		};
	}
	class Primaris_SR_WhiteScars: Primaris_SM_SR_1
	{
		author="Hummus, Barbon";
		displayName="Primaris WS (Mk.10)";
		hiddenSelectionsTextures[]=
		{
			"SR_Primaris\Textures\WS_PrimArmour.paa",
			"SR_Uniforms\Textures\SR_Armour1.paa"
		};
	}
}; // End of CfgVechicle
